### ISSUE TITLE
wavフォルダの使い道と特定ユーザーの読み上げに特定音声を流す方法

### ISSUE THREAD

**Issue by KonohanaSakuya2680** [omatztw/gomatalk#10]
試しにwavにwavファイルを入れ、buildし、%abで読み上げ対象に自分を設定してみましたがwav音声が流れません。
どうしたら流れるのでしょうか？

**Comment by omatztw** [comment]
ab 123456781234567890 "1.wav,2.wav" 
のように、ユーザーIDとwavフォルダに置いたwavのファイル名を指定してください。

使い道は自由です。

**Comment by KonohanaSakuya2680** [comment]
""が必要だったんですね、ありがとうございます。
wavを再生した後はコメントは読まれない仕様なのでしょうか？
