### ISSUE TITLE
dbファイルの中身を見たい

### ISSUE THREAD

**Issue by KonohanaSakuya2680** [omatztw/gomatalk#11]
一般に出回っているdbファイルを覗くソフトウェアを使うと、「これはdbファイルではありません」と出て覗けません。
何のソフトを使えば見れるでしょうか？

**Comment by omatztw** [comment]
使ったことありませんが、以下はどうでしょう？

https://github.com/konoui/boltdb-exporter

**Comment by omatztw** [comment]
[bolt](https://github.com/boltdb/bolt)というDBを使っていますので、周辺ツールなどはご自身で検索してみてください。

**Comment by KonohanaSakuya2680** [comment]
ありがとうございます！無事に中身を見れました。
誰が単語を登録したのかはわからない感じですかね？

**Comment by omatztw** [comment]
誰が登録したかどうかはDBに記録していないのでわからないですね。
