### ISSUE TITLE
commands.goを編集しても反映されない

### ISSUE THREAD

**Issue by KonohanaSakuya2680** [omatztw/gomatalk#8]
入退出時のメッセージを変更したいのですが、できません。

**Comment by omatztw** [comment]
コードを変更した際にはコンパイルし直す必要があります。
docker-composeで定義されているイメージは当方であらかじめビルドしたものなのでコード変更は反映されません。

Dockerfileも梱包されているので、ご自身でコンパイルする場合は参考にしてください。
docker-compose.yml を書き換えてローカルコードをビルドする様にしても良いと思います。

```diff
- image: omatztw/gomatalk
+ build: .
```

**Comment by KonohanaSakuya2680** [comment]
docker-compose.ymlを書き換えましたがビルドに失敗します…
![SnapCrab_NoName_2021-12-2_15-34-29_No-00](https://user-images.githubusercontent.com/47909539/144370501-7dab41f9-451f-40c6-ad57-38cf0aa624c3.png)
![SnapCrab_NoName_2021-12-2_15-32-44_No-00](https://user-images.githubusercontent.com/47909539/144370536-c8aea125-b301-4898-85b2-241e50a471d9.png)
…

**Comment by KonohanaSakuya2680** [comment]
無事できました！
ありがとうございました。
